package car_rental_system;

import java.sql.*;
import java.util.ArrayList;

public class Reservation {
	
	// Reservation fields
	private int id;
	private String location;
	private Date puDate;
	private String pTime;
	private Date rDate;
	private String rTime;
	private String vehicle;
	
	/*
	 * Creates a new Reservation in the DB and returns
	 * a corresponding Reservation object.
	 */
	public static Reservation create(String location, Date puDate, String pTime, Date rDate, String rTime, String vehicle ) {
		
		Reservation reservation = null;
		
		Connection conn = Database.connect();
		try {
			Statement stmt = conn.createStatement();
			
				String sql = "INSERT INTO Reservation" + "Values('"+ location +"', '"+ puDate +"', '"+ pTime +"', '"+ rDate +"', '"+ rTime +"', '"+ vehicle +"' )";
				//assuming that int id is auto generated in mysql as a unique identifier, this returns that id.
				id = stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
				
		     }
		catch(SQLException e) {
			System.out.println(e.getMessage());
		}
			
		//reservation = Reservation.getID(id);//where do i get id from? is it primary key, autogenerated in mysql?
		reservation = Reservation.getByID(id);
		
		return reservation;		
	}
	
	/*
	 * Selects reservation by a given reservation ID
	 * and returns a Reservation object.
	 */
	public static Reservation getById(int id) {
		
		// Create null Reservation
		Reservation reservation = null;
		
		// Query the database for a matching Reservation
		Connection conn = Database.connect();
		try {
			
				Statement stmt = conn.createStatement();
			
				String sql = "SELECT * FROM 'Reservation' WHERE 'id' = '"+id+"';				
				ResultSet rs = stmt.executeQuery(sql);
				
				if(rs.next())
				{
					reservation = new Reservation();
					reservation.id = result.getInt("id");
					reservation.location = result.getString("location");
					reservation.puDate = result.getDate("puDate");
					reservation.pTime = result.getString("pTime");
					reservation.rDate = result.getDate("rDate");
					reservation.rTime = result.getString("rTime");
					reservation.vehicle = result.getString("vehicle");
				}
				
		     }
		catch(SQLException e) {
			System.out.println(e.getMessage());
		}
		
		return reservation;
		
	}
	
	/*
	 * Selects all reservations by a given user ID and 
	 * returns them in an ArrayList<Reservation> object.
	 */
	public static ArrayList<Reservation> getByUserId(int userId) {
		
		// Create ArrayList for reservations
		ArrayList<Reservation> reservations = new ArrayList<Reservation>();
		
		
		
		// Query the database for a matching Reservations and store each in reservations
		
		return reservations;
		
	}
	
	/*
	 * Cancels the Reservation specified
	 * by the id.
	 */
	public static void cancel(int id) {
		Connection conn = Database.connect();
		try {
			Statement stmt = conn.createStatement();
			
				String sql = "DELETE FROM Reservation" + "WHERE id = '"+id+"';
				stmt.executeUpdate(sql);
				
		     }
		catch(SQLException e) {
			System.out.println(e.getMessage());
		}
		
	}
	
	/*
	 * Cancels the Reservation.
	 */
	public void cancel() {
		Reservation.cancel(this.id);
	}
	
}
